apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deployer
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: This is a system-generated parameter and is required for use in
          application releases. Refer to
          https://docs.cloudbees.com/docs/cloudbees-platform/latest/applications/releases#manifest
          for the expected format
metadata:
  stages/v1alpha1:
    - name: qa
      jobs:
        - deploy-to-qa
    - name: pre-prod
      jobs:
        - deploy-to-pre-prod
    - name: prod
      jobs:
        - deploy-to-prod
jobs:
  deploy-to-qa:
    environment: qa
    uses: <repo>/.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ cloudbees.job.environment }}
  deploy-to-pre-prod:
    needs:
      - deploy-to-qa
    environment: pre-prod
    uses: <repo>/.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ cloudbees.job.environment }}
  deploy-to-prod:
    needs:
      - deploy-to-pre-prod
    environment: prod
    uses: <repo>/.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ cloudbees.job.environment }}
