apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deployer

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      manifest:
        type: string
        required: true

jobs:
  qa-python-hello-World-test-docker-artifact-2:
    if: ${{ fromJSON(inputs.manifest)['qa-python-hello-World']['qa-python-hello-Worldtest-docker-artifact-2'].deploy }}
    uses: https://github.com/cbp-test-QA-automation/qa-python-hello-World.git/.cloudbees/workflows/deploy.yaml
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['qa-python-hello-World']['qa-python-hello-Worldtest-docker-artifact-2'].id }}
      environment: ${{ inputs.environment }}
  qa-python-hello-World-qa-python-helloworld:
    if: ${{ fromJSON(inputs.manifest)['qa-python-hello-World']['qa-python-hello-Worldqa-python-helloworld'].deploy }}
    uses: https://github.com/cbp-test-QA-automation/qa-python-hello-World.git/.cloudbees/workflows/deploy.yaml
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['qa-python-hello-World']['qa-python-hello-Worldqa-python-helloworld'].id }}
      environment: ${{ inputs.environment }}
  qa-python-hello-World-index_docker_io_cbpautomation_python-hello-world-docker:
    if: ${{ fromJSON(inputs.manifest)['qa-python-hello-World']['qa-python-hello-Worldindex.docker.io/cbpautomation/python-hello-world-docker'].deploy }}
    uses: https://github.com/cbp-test-QA-automation/qa-python-hello-World.git/.cloudbees/workflows/deploy.yaml
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['qa-python-hello-World']['qa-python-hello-Worldindex.docker.io/cbpautomation/python-hello-world-docker'].id }}
      environment: ${{ inputs.environment }}
  qa-python-hello-World-ghcr_io_cbp-test-qa-automation_qa-python-hello-world:
    if: ${{ fromJSON(inputs.manifest)['qa-python-hello-World']['qa-python-hello-Worldghcr.io/cbp-test-qa-automation/qa-python-hello-world'].deploy }}
    uses: https://github.com/cbp-test-QA-automation/qa-python-hello-World.git/.cloudbees/workflows/deploy.yaml
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['qa-python-hello-World']['qa-python-hello-Worldghcr.io/cbp-test-qa-automation/qa-python-hello-world'].id }}
      environment: ${{ inputs.environment }}
  qa-python-hello-World-cbpautomation_python-hello-world-docker:
    if: ${{ fromJSON(inputs.manifest)['qa-python-hello-World']['qa-python-hello-Worldcbpautomation/python-hello-world-docker'].deploy }}
    uses: https://github.com/cbp-test-QA-automation/qa-python-hello-World.git/.cloudbees/workflows/deploy.yaml
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['qa-python-hello-World']['qa-python-hello-Worldcbpautomation/python-hello-world-docker'].id }}
      environment: ${{ inputs.environment }}
  qa-python-hello-World-cbp-test-manual_qa-python-hello-World:
    if: ${{ fromJSON(inputs.manifest)['qa-python-hello-World']['qa-python-hello-Worldcbp-test-manual/qa-python-hello-World'].deploy }}
    uses: https://github.com/cbp-test-QA-automation/qa-python-hello-World.git/.cloudbees/workflows/deploy.yaml
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['qa-python-hello-World']['qa-python-hello-Worldcbp-test-manual/qa-python-hello-World'].id }}
      environment: ${{ inputs.environment }}
