apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: stage-env-approval
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: This is a system-generated parameter and is required for use in
          application releases. Refer to
          https://docs.cloudbees.com/docs/cloudbees-platform/latest/applications/releases#manifest
          for the expected format
metadata:
  stages/v1alpha1:
    - name: QA
      jobs:
        - Deploy-QA
        - qa-approval
jobs:
  qa-approval:
    needs: Deploy-QA
    environment: approval_QA
    steps:
      - run: 'echo "Staged approval based on ENV: ${{ jobs.environment }}"'
        uses: docker://golang:1.20.3-alpine3.17
        name: Environment based approval
  Deploy-QA:
    environment: QA
    steps:
      - run: echo "Deploying.... to ${{ job.environment }}"
        uses: docker://golang:1.20.3-alpine3.17
        name: Deploy
